# Generated by Django 3.0.5 on 2021-09-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210911_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
